2020-06-21 19:47:39,120 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute']
2020-06-21 19:47:39,146 DEBUG    root            Loaded Command Group: [u'gcloud', u'compute', u'ssh']
2020-06-21 19:47:39,150 DEBUG    root            Running [gcloud.compute.ssh] with arguments: [[USER@]INSTANCE: "dl-1-vm"]
2020-06-21 19:47:39,334 WARNING  root            The public SSH key file for gcloud does not exist.
2020-06-21 19:47:39,335 WARNING  root            The private SSH key file for gcloud does not exist.
2020-06-21 19:47:39,335 WARNING  root            You do not have an SSH key for gcloud.
2020-06-21 19:47:39,336 WARNING  root            SSH keygen will be executed to generate a key.
2020-06-21 19:47:58,214 DEBUG    root            Running command [/usr/bin/ssh-keygen -t rsa -f /Users/shu/.ssh/google_compute_engine].
2020-06-21 19:47:58,215 DEBUG    root            Executing command: [u'/usr/bin/ssh-keygen', u'-t', u'rsa', u'-f', u'/Users/shu/.ssh/google_compute_engine']
2020-06-21 19:48:06,569 DEBUG    root            (gcloud.compute.ssh) Could not fetch resource:
 - The resource 'projects/kaggle-backstage/zones/us-east1-b/instances/dl-1-vm' was not found
Traceback (most recent call last):
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 807, in Run
    resources = command_instance.Run(args)
  File "/Users/shu/google-cloud-sdk/lib/surface/compute/ssh.py", line 163, in Run
    instance = ssh_helper.GetInstance(client, instance_ref)
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/command_lib/compute/ssh_utils.py", line 497, in GetInstance
    return client.MakeRequests([request])[0]
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/client_adapter.py", line 103, in MakeRequests
    errors, error_message='Could not fetch resource:')
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 119, in RaiseToolException
    RaiseException(problems, calliope_exceptions.ToolException, error_message)
  File "/Users/shu/google-cloud-sdk/lib/googlecloudsdk/api_lib/compute/utils.py", line 131, in RaiseException
    errors))
ToolException: Could not fetch resource:
 - The resource 'projects/kaggle-backstage/zones/us-east1-b/instances/dl-1-vm' was not found

2020-06-21 19:48:06,574 ERROR    root            (gcloud.compute.ssh) Could not fetch resource:
 - The resource 'projects/kaggle-backstage/zones/us-east1-b/instances/dl-1-vm' was not found

